# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AdobeCenter.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdobeCenter(object):
    def setupUi(self, AdobeCenter):
        AdobeCenter.setObjectName("AdobeCenter")
        AdobeCenter.resize(832, 700)
        self.textBrowser = QtWidgets.QTextBrowser(AdobeCenter)
        self.textBrowser.setGeometry(QtCore.QRect(290, 390, 271, 131))
        self.textBrowser.setStyleSheet("color: rgb(104, 235, 255);\n"
"background: transparent;")
        self.textBrowser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser.setObjectName("textBrowser")
        self.labelMessage = QtWidgets.QLabel(AdobeCenter)
        self.labelMessage.setGeometry(QtCore.QRect(300, 320, 231, 20))
        self.labelMessage.setStyleSheet("color: rgb(43, 204, 249);")
        self.labelMessage.setText("")
        self.labelMessage.setObjectName("labelMessage")
        self.labelProgress = QtWidgets.QProgressBar(AdobeCenter)
        self.labelProgress.setGeometry(QtCore.QRect(300, 350, 231, 2))
        self.labelProgress.setMaximumSize(QtCore.QSize(16777215, 2))
        self.labelProgress.setStyleSheet("QProgressBar {\n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: rgb(71, 167, 225);\n"
"}")
        self.labelProgress.setProperty("value", 0)
        self.labelProgress.setTextVisible(False)
        self.labelProgress.setObjectName("labelProgress")

        self.retranslateUi(AdobeCenter)
        QtCore.QMetaObject.connectSlotsByName(AdobeCenter)

    def retranslateUi(self, AdobeCenter):
        _translate = QtCore.QCoreApplication.translate
        AdobeCenter.setWindowTitle(_translate("AdobeCenter", "Form"))
        self.textBrowser.setHtml(_translate("AdobeCenter", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">Thomas Koll, Seetharaman Narayanan, Rssell Wliams, Jackie Lincoln Ovryang. Alan Enckson, Ivy Mak, Sarah Kong, Jermry Harrs, Mike Shaw, Thomas Ruark, Domnita Petri, David Mohr, Yukie Takahashi, David Dobish, Steven E. Snyder, John Peterson, Adam Jenugim, Tom Attic Judy Severance, Yuko Kagita, Foster Brereton, Meredith P. Stotzner, Tai Luxon, Vinod Balakrishnan Tm Wight, John Worthington, Mark Maguire, Maria Yap, Pam dark, B.Winston Hndnickson, Pete Falo, Dave Polaschek, Kkyoko Iooda, Kellisa Sandoval, Steve Guilhamet, Daniel Presedo, Sarah Stuckey,</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AdobeCenter = QtWidgets.QWidget()
    ui = Ui_AdobeCenter()
    ui.setupUi(AdobeCenter)
    AdobeCenter.show()
    sys.exit(app.exec_())
